server:
  port: 8080

spring:
  application:
    name: luckxpress-admin
  profiles:
    active: dev
  datasource:
    url: jdbc:h2:mem:luckxpress_dev
    driver-class-name: org.h2.Driver
    username: sa
    password: 
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect

logging:
  level:
    com.luckxpress: DEBUG
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

# Custom application properties
luckxpress:
  admin:
    default-page-size: 20
    max-page-size: 100
  security:
    jwt:
      secret: luckxpress_secret_key_2024
      expiration: 86400000 # 24 hours
