apiVersion: v1
kind: ServiceAccount
metadata:
  name: luckxpress-backend
  namespace: luckxpress-prod
  labels:
    app: luckxpress
    component: backend

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: luckxpress-prod
  name: luckxpress-backend-role
rules:
- apiGroups: [""]
  resources: ["configmaps", "secrets"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: luckxpress-backend-rolebinding
  namespace: luckxpress-prod
subjects:
- kind: ServiceAccount
  name: luckxpress-backend
  namespace: luckxpress-prod
roleRef:
  kind: Role
  name: luckxpress-backend-role
  apiGroup: rbac.authorization.k8s.io
